@Properties.Api_HostAddress = http://localhost:5296

### Listado de propiedades (paginado)
GET {{Properties.Api_HostAddress}}/api/properties?pageNumber=1&pageSize=15
Accept: application/json

###
### Listado con filtros
GET {{Properties.Api_HostAddress}}/api/properties?pageNumber=1&pageSize=15&propertyTypeId=&cityId=&stratum=
Accept: application/json

###
